### ISSUE TITLE
- [ ] Realizar Prototipo baja o mediana fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_cv_ppi2020#10]

**Comment by carlosfloresortega** [comment]
@JohnFlorez25, el prototipo de mediana fidelidad ha sido realizo con éxito.

**Comment by JohnFlorez25** [comment]
Evidencian avances en los prototipos, se dan directrices para complementar con el ranking de posiciones, insignias o trofeos, para complementar de acuerdo al alcance del proyecto.
