### ISSUE TITLE
- [ ] Realizar validaciones con 5 usuarios

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_cv_ppi2020#11]

**Comment by AnaAgudelo05** [comment]
@JohnFlorez25 Ya realicé las validaciones con 5 usuarios.

**Comment by AnaAgudelo05** [comment]
@JohnFlorez25 Ya realicé el cuadro de metodología OOUX

**Comment by JohnFlorez25** [comment]
@AnaAgudelo05 revicé y aprobé las historias de usuario
