### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_cv_ppi2020#2]

**Comment by carlosfloresortega** [comment]
Ya el diagrama de pescado fue realizado

**Comment by JohnFlorez25** [comment]
Mejorar la identificación del problema para tener causas claras de ese problema

**Comment by JohnFlorez25** [comment]
Pendiente de avances, no se hicieron las correcciones ni se tomaron en cuenta las recomendaciones estípuladas

**Comment by JohnFlorez25** [comment]
Mejorar la identificación del problema una idea puntual por ejemplo: "los resultados de los estudiantes. en la materia de química no son muy buenos", las causas están bien identificadas y ayudan para la declaración de la situación del problema.
