### ISSUE TITLE
Declarar la situación del problema

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_cv_ppi2020#3]

**Comment by carlosfloresortega** [comment]
Ya se realizo la declaración del problema

**Comment by JohnFlorez25** [comment]
Realizar la declaración del problema de acuerdo a lo planteado en el diagrama de espina de pescado

**Comment by JohnFlorez25** [comment]
Pendiente de avances, no se hicieron las correcciones ni se tomaron en cuenta las recomendaciones estípuladas

**Comment by JohnFlorez25** [comment]
@Yato1850 @carlosfloresortega @AnaAgudelo05 recuerden que la declaración de la situación del problema esta compuesta por tres partes, el  problema que se identifico en el diagrama de espina de pescado, las causas más relevantes que le ayuden a complementar la situación del problema y en que tiene efecto
