### ISSUE TITLE
Describir cada uno de los interesados

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_cv_ppi2020#4]

**Comment by AnaAgudelo05** [comment]
Profesor @JohnFlorez25  Ya está lista la descripción de los interesados

**Comment by JohnFlorez25** [comment]
Es posible identificar otros dos interesados como mínimo

**Comment by JohnFlorez25** [comment]
Pendiente de avances, no se hicieron las correcciones ni se tomaron en cuenta las recomendaciones estípuladas
