### ISSUE TITLE
Construir el Tablero de visión del producto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_cv_ppi2020#5]

**Comment by AnaAgudelo05** [comment]
Profesor @JohnFlorez25  El tablero de visión del producto ya está listo

**Comment by JohnFlorez25** [comment]
Falta información relevante del cuadro de visión, como la descripción de visión del producto, se pueden identificar más necesidades, características y beneficios

**Comment by JohnFlorez25** [comment]
Pendiente de avances, no se hicieron las correcciones ni se tomaron en cuenta las recomendaciones estípuladas

**Comment by JohnFlorez25** [comment]
Ampliar la descripción de la visión del producto de acuerdo a la regla compartida en al guía del análisis del problema.
