### ISSUE TITLE
Realizar Historias de Usuario y criterios de aceptación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_cv_ppi2020#8]

**Comment by AnaAgudelo05** [comment]
@JohnFlorez25  Ya realicé en Excel las Historias de Usuario junto con los criterios de aceptación.

**Comment by JohnFlorez25** [comment]
@AnaAgudelo05 Mínimo 10 historias de usuario, y corroborar que esas historias correspondan con las funcionalidades claves de la aplicación.

**Comment by AnaAgudelo05** [comment]
@JohnFlorez25 Ya completé las 10 historias de usuario.

**Comment by AnaAgudelo05** [comment]
> @ AnaAgudelo05 Mínimo 10 historias de usuario, y corroborar que esas historias correspondan con las funcionalidades claves de la aplicación.

Ya las completé, profesor
